stages:
  - build
  - docker_deployment

variables:
  STAGING_ENV_FILE: .env.staging

build:
  stage: build
  image: node:20-alpine
  script:
    - npm install
    - npm run build

build-docker-image-staging:
  stage: docker_deployment
  script:
    # Stop and remove the existing container if it exists
    - docker stop carenest-frontend-staging || true
    - docker rm carenest-frontend-staging || true

    # Check if Dockerfile exists
    - test -f Dockerfile || { echo "Error: Dockerfile not found"; exit 1; }

    # Build the Docker image with the staging environment configuration
    - docker build --build-arg ENV_FILE=$STAGING_ENV_FILE -t carenest-fe:staging .

    # Run the container for staging
    - docker run --name carenest-frontend-staging -p 5174:5173 -d carenest-fe:staging
  only:
    - main
