stages:
  - build
  - docker_deployment

variables:
  STAGING_ENV_FILE: .env.staging
  REACT_APP_BACKEND_URL: http://localhost:8090

build:
  stage: build
  image: node:20-alpine
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

build-docker-image-staging:
  stage: docker_deployment
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker stop carenest-frontend-staging || true
    - docker rm carenest-frontend-staging || true

    - docker build --build-arg REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL -t carenest-fe:staging .
    - docker run --name carenest-frontend-staging -p 5174:5173 -d carenest-fe:staging
  only:
    - main