stages:
  - build
  - docker_deployment

variables:
  STAGING_ENV_FILE: .env.staging

build:
  stage: build
  image: node:20-alpine
  script:
    - npm install
    - npm run build

build-docker-image-staging:
  stage: docker_deployment
  script:
    - |
      try {
          docker stop carenest-frontend-staging
      } catch {
          Write-Host "Container not running or does not exist."
      }
    - |
      try {
          docker rm carenest-frontend-staging
      } catch {
          Write-Host "Container not found."
      }

    # Ensure Dockerfile exists
    - if (!(Dockerfile)) { Write-Error "Dockerfile not found"; exit 1 }

    # Build the Docker image for staging
    - docker build --build-arg ENV_FILE=$STAGING_ENV_FILE -t carenest-fe:staging .

    # Run the container for staging
    - docker run --name carenest-frontend-staging -p 5174:5173 -d carenest-fe:staging
  only:
    - main
