stages:
  - build
  - test
  - docker_deployment

build:
  stage: build
  image: node:20-alpine
  script:
    - npm install
    - npm run build -- --mode=staging

e2e-tests:
  stage: test
  image: cypress/included:12.16.0
  dependencies:
    - build
  variables:
    CYPRESS_BASE_URL: "http://localhost:5173"
  script:
    - npm install
    - npx cypress run
  only:
    - main

build-docker-image:
  stage: docker_deployment
  variables:
    REACT_APP_BACKEND_URL: "http://localhost:8090"
  script:
    - docker stop carenest-frontend || true && docker rm carenest-frontend || true
    - docker build --build-arg REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL -t carenest-fe:staging .
    - docker run --name carenest-frontend -p 5173:5173 -d carenest-fe:staging
  only:
    - main
